LIBDIR = $(PREFIX)/lib/
OBJDIR = ./$(PREFIX)/objs/
ENGINE_LIB = engine
CPP_FILES = $(wildcard *.cpp, *.cpp)
HDR = $(wildcard *.h, *.h)
OBJ_FILES = $(patsubst %.cpp, %.o, $(CPP_FILES))
OBJ = $(addprefix $(OBJDIR), $(OBJ_FILES))
CCFLAGS = -static -s -c -O3 -D NDEBUG
