.PHONY : $(PROJECT)
$(PROJECT): $(TARGET)

$(OBJDIR) $(TARGETDIR):
	mkdir -p $@

$(OBJDIR)%.o: %.cpp $(HDR)
	$(COMPILE) $< -o $@

.PHONY : clean	
clean:
	rm -f $(OBJ) $(TARGET)

$(OBJ): |$(OBJDIR)
$(TARGET): |$(TARGETDIR)
