PREFIX = gcc-x64
LIBDIR = $(PREFIX)/lib/
OBJDIR = ./$(PREFIX)/objs/
ENGINE_LIB = engine
CPP_FILES = $(wildcard *.cpp, *.cpp)
HDRS = $(wildcard *.h, *.h)
OBJ_FILES = $(patsubst %.cpp, %.o, $(CPP_FILES))
OBJ = $(addprefix $(OBJDIR), $(OBJ_FILES))

CCC = x86_64-w64-mingw32-g++.exe
CCFLAGS = -static -s -c -O3 -D NDEBUG
